# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Handle API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specify the Node.js version for functions
[build.environment]
  NODE_VERSION = "18"

# Configure function bundle settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3"]

# Add caching for improved performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
