
# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specify the Node.js version for functions
[build.environment]
  NODE_VERSION = "18"
